
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://daqvphzqrnsxqthggwrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhcXZwaHpxcm5zeHF0aGdnd3J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMjg2MzgsImV4cCI6MjA1OTcwNDYzOH0.WBW0ayOMlY4Rk5k7Ky1UnWqqB-1ya8kB0xtMKY1hSgc";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Manually add type definitions for tables not yet in the Database type
export interface ChangelogEntry {
  id: string;
  version: string;
  description: string[];
  created_at: string;
  updated_at?: string;
}

// Add changelog_entries table to Database type
declare module './types' {
  export interface Database {
    public: {
      Tables: {
        changelog_entries: {
          Row: ChangelogEntry;
          Insert: Omit<ChangelogEntry, 'id' | 'created_at' | 'updated_at'>;
          Update: Partial<Omit<ChangelogEntry, 'id'>>;
        };
      };
    };
  }
}

