
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://daqvphzqrnsxqthggwrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhcXZwaHpxcm5zeHF0aGdnd3J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMjg2MzgsImV4cCI6MjA1OTcwNDYzOH0.WBW0ayOMlY4Rk5k7Ky1UnWqqB-1ya8kB0xtMKY1hSgc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
