// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://daqvphzqrnsxqthggwrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhcXZwaHpxcm5zeHF0aGdnd3J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMjg2MzgsImV4cCI6MjA1OTcwNDYzOH0.WBW0ayOMlY4Rk5k7Ky1UnWqqB-1ya8kB0xtMKY1hSgc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Manually add type definitions for tables not yet in the Database type
export interface ChangelogEntry {
  id: string;
  version: string;
  description: string[];
  created_at: string;
  updated_at?: string;
}

// SQL for creating notifications table:
/* 
CREATE TABLE IF NOT EXISTS notifications (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  ticket_id UUID REFERENCES tickets(id) ON DELETE CASCADE,
  ticket_title TEXT,
  content TEXT NOT NULL,
  type TEXT CHECK (type IN ('rating_request', 'status_change', 'new_message', 'new_ticket')),
  read BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX notifications_user_id_idx ON notifications (user_id);
CREATE INDEX notifications_read_idx ON notifications (read);
*/
